Rename --options to --choices

diff --git a/rofi-power-menu b/rofi-power-menu
--- a/rofi-power-menu
+++ b/rofi-power-menu
@@ -29,7 +29,7 @@ confirm=false
 dryrun=false
 
 # Parse command-line options
-parsed=$(getopt --options=h --longoptions=help,dry-run,confirm,options: --name "$0" -- "$@")
+parsed=$(getopt --options=h --longoptions=help,dry-run,confirm,choices: --name "$0" -- "$@")
 if [ $? -ne 0 ]; then
     echo 'Terminating...' >&2
     exit 1
@@ -41,19 +41,19 @@ while true; do
         "-h"|"--help")
             echo "rofi-power-menu - a power menu mode for Rofi"
             echo
-            echo "Usage: rofi-power-menu [--options CMDS] [--confirm] [--dry-run]"
+            echo "Usage: rofi-power-menu [--choices CHOICES] [--confirm] [--dry-run]"
             echo
-            echo "Use with Rofi in script mode. For instance:"
+            echo "Use with Rofi in script mode. For instance, to show shutdown and reboot choices:"
             echo
-            echo "rofi -show powermenu -modi \"powermenu:rofi-power-menu --options=shutdown/reboot\""
+            echo "  rofi -show powermenu -modi \"powermenu:rofi-power-menu --choices=shutdown/reboot\""
             echo
             echo "Available options:"
-            echo "  --dry-run  Don't perform the selected action but print it to stderr."
-            echo "  --options  Show only the selected choices in given order. Use / as the separator."
-            echo "             Available choices are lockscreen, logout, suspend, hibernate, reboot"
-            echo "             and shutdown."
-            echo "  --confirm  Require confirmation."
-            echo "  -h,--help  Show this help text."
+            echo "  --dry-run          Don't perform the selected action but print it to stderr."
+            echo "  --choices CHOICES  Show only the selected choices in given order. Use / as the separator."
+            echo "                     Available choices are lockscreen, logout, suspend, hibernate, reboot"
+            echo "                     and shutdown. By default, all choices are shown."
+            echo "  --confirm          Require confirmation."
+            echo "  -h,--help          Show this help text."
             exit 0
             ;;
         "--dry-run")
@@ -66,11 +66,11 @@ while true; do
             shift 1
             continue
             ;;
-        "--options")
-            IFS='/' read -ra options <<< "$2"
+        "--choices")
+            IFS='/' read -ra choices <<< "$2"
             show=""
-            for option in "${options[@]}"; do
-                case $option in
+            for choice in "${choices[@]}"; do
+                case $choice in
                     "lockscreen")
                         show="$show$lockscreen\n" ;;
                     "logout")
@@ -84,7 +84,7 @@ while true; do
                     "shutdown")
                         show="$show$shutdown\n" ;;
                     *)
-                        echo "Invalid option: $option" >&2
+                        echo "Invalid choice: $choice" >&2
                         exit 1
                         ;;
                 esac
